version: '3.3'
services:
  mysql:
    build:
      context: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      # it is not a problem to check in password in clear text:
      # the mysql service is only accessible within this namespace.
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - database:/var/lib/
  appsrv:
    build:
      context: ./appsrv
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
    volumes:
      - appsrvstorage:/var/lib/appsrvstorage/
  express:
      build:
        context: ./express
volumes:
  database:
  appsrvstorage:
