GET http://localhost:8080/api/person
Accept: application/json

###
GET http://localhost:8080/api/person/3
Accept: application/json

###
GET http://localhost:8080/api/school/2
Accept: application/json

